import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/footer";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen h-auto bg-gradient-to-b from-white to-green-300 ">
          <div className="h-24 ">
            <Navbar />
          </div>{" "}
          <div className="h-{calc(100vh-6rem)} bg-red ">{children}</div>
        </div>
      </body>
    </html>
  );
}
